Drop Support for PySide 6.7 (for now). multiData() uses QModelRoleDataSpan, which is present since Qt 6.0, but somehow isn't availabel in 6.7: ImportError: cannot import name 'QModelRoleDataSpan' from 'PySide6.QtCore'
FossilOrigin-Name: 9a9d4f48294dcffe6af0f72e350f7c11b0452d8d7c8c834bdf173ea0e70b1177